### ISSUE TITLE
Manually create fixtures for ZenodoRDM

### ISSUE THREAD

**Issue by zzacharo** [zenodo/zenodo-rdm#52]
-  [ ] OAI-PMH sets
- [ ] Communities and their user
- [ ] Vocabularies (resource types, description types, funders, grants, ORCID, ROR)

**Comment by slint** [comment]
### OAI-PMH sets

```yaml
- name: "OpenAIRE Data"
  spec: "openaire_data" 
  search_pattern: "resource_type.type:dataset"
```

### Communities

> To be added from https://github.com/zenodo/zenodo/blob/master/zenodo/modules/fixtures/data/communities.json

### Vocabularies

- Licenses (already imported by default fixtures)
- Funders (a subset is already imported by default fixtures)
